### ISSUE TITLE
Deployed project on local, running as expected but when changing host to ip address it does not work

### ISSUE THREAD

**Issue by technicalbirdVayuz** [PythonicCafe/dokku-prerender#1]
Example: 

- curl localhost:3000/https://website.com/abcd - works fine
- curl website.com:3000/https://website.com/abcd - Failed to connect, connection time out, Port 3000 is also open, request does not come in logs too

**Comment by turicas** [comment]
Did you use dokku and all the instructions on this repository or you just created the issue here as a continuation of https://github.com/prerender/prerender/issues/774?

**Comment by technicalbirdVayuz** [comment]
I read the dokku documentation & implemented this on local, its working fine, not working on production

**Comment by technicalbirdVayuz** [comment]
It works, thanks, got one error posting that in different thread
